spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/swordie
    username: root
    password: nash3227
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database: mariadb
    database-platform: org.hibernate.dialect.MariaDBDialect
